### ISSUE TITLE
Poetry-built wheels pollute users' `site-packages/` directory

### ISSUE THREAD

**Issue by Qonfused** [Qonfused/OCE-Build#12]
Currently blocked by Poetry's include/exclude paths behavior for the build wheel. The current behavior with Poetry's include/exclude paths works as expected including files for the sdist destination, but not for the wheel destination.

Related issues in tracking:
- https://github.com/python-poetry/poetry/issues/2015#issuecomment-792409756
- https://github.com/python-poetry/poetry/issues/4583)

The output paths in the wheel appear to be determined by the relative paths of included directories from the root pyproject.toml file, which if containing files located in the project root will pollute the user's `site-packages/` and `site-packages/resources` directories upon installation!

Additionally, currently suggested workarounds like symlinks aren't compatible between Windows and macOS/Linux environments.

**Comment by Qonfused** [comment]
A possible workaround is to use a `packages:` field in the pyproject.toml that points to a build staging area where the package structure is amended to be compatible with setuptools. However, this would require rewriting import paths for `third_party.*` or `ocebuild_cli.*`, including cross-references with the base ocebuild library.

<details><summary>The current project structure appears as below: (collapsed)</summary>

```
├── pyproject.toml
├── README.md
├── ocebuild
│   ├── __init__.py
│   └── ...
├── ocebuild_cli
│   ├── __init__.py
│   ├── __main__.py
│   └── ...
└── third_party
    ├── __init__.py
    ├── cpython
    │   ├── __init__.py
    │   └── ...
    └── ...
```

</details>

<details><summary>Which would need to be amended to: (collapsed)</summary>

```
├── pyproject.toml
├── README.md
└── ocebuild
    ├── __init__.py
    ├── cli
    │   ├── __init__.py
    │   ├── __main__.py
    │   └── ...
    ├── third_party
    │    ├── __init__.py
    │    ├── cpython
    │    │   ├── __init__.py
    │    │   └── ...
    │    └── ...
    └── ...
```

</details>

The implementation for the wheel would look like this in the pyproject.toml:
```toml
[tool.poetry]
packages = [
  # Redirect poetry to staging area for sdist and wheel distribution:
  { include = "ocebuild",     from = "dist/staging",  format = "wheel" }
]
```

Although it remains unclear whether to handle this sooner in the sdist preparation rather than redirecting for the wheel.

**Comment by Qonfused** [comment]
An alternate sdist tree can still be built with the use of poetry's undocumented build hooks (i.e. `tool.poetry.build.script`). This only relies on [poetry-core](https://github.com/python-poetry/poetry-core) and can still be built by a PEP-517 front-end like PIP.

For example, this hook can point to a `ci/hooks/build.py` file that is used to create the staging area (and is automatically included in the sdist by poetry):

<details><summary><code>pyproject.toml</code></summary>

```toml
[tool.poetry]
name          = "ocebuild"
version       = "0.0.0-dev"
description   = "Portable OpenCore EFI dependency & build manager."
authors       = [ "Cory Bennett <csquaredbennett@gmail.com>" ]
# ... omitted for brevity
packages      = [
  # Include required modules for the source distribution:
  { include = "ocebuild",     from = ".",             format = "sdist" },
  { include = "ocebuild_cli", from = ".",             format = "sdist" },
  { include = "third_party",  from = ".",             format = "sdist" },
  # Redirect poetry to staging area for the wheel distribution:
  { include = "ocebuild",     from = "dist/staging",  format = "wheel" }
]

[tool.poetry.build]
generate-setup-file = false
script = "ci/hooks/build.py"

[build-system]
requires      = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

</details>

<details><summary><code>ci/hooks/build.py</code></summary>

```py
from functools import partial

from shutil import rmtree, copytree as _copytree

if __name__ == '__main__':
  copytree = partial(_copytree, dirs_exist_ok=True)

  staging_path = 'dist/staging'
  rmtree(staging_path, ignore_errors=True)

  copytree('ocebuild',      f'{staging_path}/ocebuild')
  copytree('ocebuild_cli',  f'{staging_path}/ocebuild/cli')
  copytree('third_party',   f'{staging_path}/ocebuild/third_party')
```

</details>

Although including the previous proposal, this introduces additional complexity as there needs to exist a `dist/staging/ocebuild/__init__.py` file before the `packages:` scope is processed.
