### ISSUE TITLE
ACPI/Delete array elements are duplicated

### ISSUE THREAD

**Issue by al3xtjames** [Qonfused/OCE-Build#19]
Hi,

I'm trying to adapt my configuration to use OCE-Build. For some reason `ocebuild build --clean` generates `dist/EFI/OC/config.plist` with duplicate elements under `ACPI/Delete`:

```yaml
ACPI:
  @override
  Delete:
    - All:                          Boolean | true
      Comment:                      String  | "Drop WPBT"
      OemTableId:                   Data    | <00000000 00000000>
      TableLength:                  Number  | 0
      TableSignature:               Data    | <57504254>
```

```
		<key>Delete</key>
		<array>
			<dict>
				<key>All</key>
				<true/>
				<key>Comment</key>
				<string>Drop WPBT</string>
				<key>Enabled</key>
				<true/>
				<key>OemTableId</key>
				<data>AAAAAAAAAAA=</data>
				<key>TableLength</key>
				<integer>0</integer>
				<key>TableSignature</key>
				<data>V1BCVA==</data>
			</dict>
			<dict>
				<key>All</key>
				<true/>
				<key>Comment</key>
				<string>Drop WPBT</string>
				<key>Enabled</key>
				<true/>
				<key>OemTableId</key>
				<data>AAAAAAAAAAA=</data>
				<key>TableLength</key>
				<integer>0</integer>
				<key>TableSignature</key>
				<data>V1BCVA==</data>
			</dict>
		</array>
```

Is this a bug, or is some other preprocessor statement supposed to be used here?
