### ISSUE TITLE
Support for empty `Data` values

### ISSUE THREAD

**Issue by al3xtjames** [Qonfused/OCE-Build#20]
Hi,

I noticed that empty `Data` values cause `ocebuild build` to fail. For example:

```yml
Kernel:
  @override
  Patch:
    # https://github.com/b00t0x/CpuTopologyRebuild/blob/master/patches_ht.plist
    - Arch:                 String  | "x86_64"
      Base:                 String  | "_cpu_thread_alloc"
      Comment:              String  | "Force enable hyper-threading (Mojave and later)"
      Count:                Number  | 1
      Find:                 Data    | <8b889401 0000>
      Identifier:           String  | "kernel"
      Limit:                Number  | 0
      Mask:                 Data    | <>
      MaxKernel:            String  | ""
      MinKernel:            String  | "18.0.0"
      Replace:              Data    | <b9ff0000 0090>
      ReplaceMask:          Data    | <>
      Skip:                 Number  | 0
```

```
        ERROR:    Failed to update config.plist: sequence item 0: expected str instance, NoneType found
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in apply_patches:130                                                                             │
│                                                                                                  │
│ in merge_configs:174                                                                             │
│                                                                                                  │
│ in read_config:64                                                                                │
│                                                                                                  │
│ in parse_yaml:243                                                                                │
│                                                                                                  │
│ in get_schema:196                                                                                │
│                                                                                                  │
│ in parse_yaml_types:43                                                                           │
│                                                                                                  │
│ in encode_data:39                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: sequence item 0: expected str instance, NoneType found
```

Commenting out `Mask` and `ReplaceMask` allows `ocebuild build` to succeed. Replacing them with valid masks (`<ffffffff ffff>`) also works but seems superfluous.
