### ISSUE TITLE
Fix handling of build entries containing periods

### ISSUE THREAD

**Issue by Qonfused** [Qonfused/OCE-Build#21]
Using periods as part of build entries in the `build.yml` file will erroneously create nested entries under the lock file containing the second half of the key following the period.

For example, using the build entries:
```yml
# build.yml
Kexts:
  "AirportItlwm-Sonoma-14.4":
    specifier: OpenIntelWireless/itlwm=^2.3.0-alpha 
    properties:
      MaxKernel: "23.99.99"
      MinKernel: "23.4.0"
  "AirportItlwm-Sonoma-14.0":
    specifier: OpenIntelWireless/itlwm=^2.3.0-alpha 
    properties:
      MaxKernel: "23.3.99"
      MinKernel: "23.0.0"
```
This will generate the below lockfile entries:
```yml
dependencies:
  Kexts:
    AirportItlwm-Sonoma-14:
      0:
        build: DEBUG
        version: 2.3.0
        url: 'https://github.com/OpenIntelWireless/itlwm/releases/download/v2.3.0-alpha/AirportItlwm-Sonoma14.0-v2.3.0-DEBUG-alpha-e886ebb.zip'
        resolution: 'OpenIntelWireless/itlwm@github:2.3.0#commit=e886ebb06658d6aee70f87e30a6bbbd0acad1f57'
        specifier: 'OpenIntelWireless/itlwm@github:^2.3.0-alpha'
        kind: Kext
        revision: '{ SHA1: e886ebb06658d6aee70f87e30a6bbbd0acad1f57 }'
      4:
        build: DEBUG
        version: 2.3.0
        url: 'https://github.com/OpenIntelWireless/itlwm/releases/download/v2.3.0-alpha/AirportItlwm-Sonoma14.4-v2.3.0-DEBUG-alpha-e886ebb.zip'
        resolution: 'OpenIntelWireless/itlwm@github:2.3.0#commit=e886ebb06658d6aee70f87e30a6bbbd0acad1f57'
        specifier: 'OpenIntelWireless/itlwm@github:^2.3.0-alpha'
        kind: Kext
        revision: '{ SHA1: e886ebb06658d6aee70f87e30a6bbbd0acad1f57 }'
```
